name: build

on:
  pull_request:
    paths-ignore:
      - "extras/assets/**"
      - "extras/hardware/**"
  push:
    paths-ignore:
      - "extras/assets/**"
      - "extras/hardware/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check clang-format conformity
        run: bash extras/ci/clang-lint.sh

      - name: Build on Arduino CLI
        run: bash extras/ci/build-arduino.sh

      - name: Build on PlatformIO
        run: bash extras/ci/build-platformio.sh
