name: docs

on:
  pull_request:
    paths-ignore:
      - "extras/assets/**"
      - "extras/hardware/**"
  push:
    paths-ignore:
      - "extras/assets/**"
      - "extras/hardware/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Doxygen
        env:
          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        run: bash extras/ci/doxygen.sh
